### ISSUE TITLE
Feature request: scripts for building in Windows

### ISSUE THREAD

**Issue by keshon** [Malwarize/retro#2]
I'm curious to test your project but I'm a Windows guy. My feature request would be: add build scripts for Windows.
Cheers!

**Comment by XORbit01** [comment]
@keshon thanks for suggesting new feature, unfortunately this project only supported on operating systems that support systemctl (which means linux), but thanks for alerting me to add a not declaring that in the README.

sincerity <3

**Comment by keshon** [comment]
Ok, got it, thanks!
